# Generated by Django 5.1.6 on 2025-02-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cus_name',
            new_name='std_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='cus_phn',
            new_name='std_phn',
        ),
    ]
